---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prod-nodejs-green
spec:
  interval: 1m0s
  releaseName: prod-nodejs-green
  targetNamespace: prod
  chart:
    spec:
      chart: ./charts/nodejs
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    app:
      name: nodejs
      env: prod
      slot: green
    image:
      replicas: "0"
      repo: docker-registry.registry:32080/nodejs
      tag: latest

