apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
namePrefix: dev-
nameSuffix: -blue
patches:
  - path: op.yaml
    target:
      kind: HelmRelease
      name: nodejs