apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../../apps/nodejs/base/
namePrefix: dev-
nameSuffix: -green
patches:
  - path: op.yaml
    target:
      kind: HelmRelease
      name: nodejs