---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: hello-vault-service
spec:
  backendType: vault
  data:
    - name: vault_pass
      key: secret/testapp/config
      property: password
    - name: vault_user
      key: secret/testapp/config
      property: username
