---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: dev-nodejs
  namespace: dev
spec:
  backendType: vault
  data:
    - name: DB_USER
      key: secret/data/testapp/config
      property: username
    - name: DB_PASS
      key: secret/data/testapp/config
      property: password
    - name: DB_HOST
      key: secret/data/testapp/config
      property: host
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: prod-nodejs
  namespace: prod
spec:
  backendType: vault
  data:
    - name: DB_USER
      key: secret/data/testapp/config
      property: password
    - name: DB_PASS
      key: secret/data/testapp/config
      property: username
    - name: DB_HOST
      key: secret/data/testapp/config
      property: host
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: drone
  namespace: devops
spec:
  backendType: vault
  data:
    - name: DRONE_GITHUB_CLIENT_ID
      key: secret/data/drone/config
      property: github_id
    - name: DRONE_GITHUB_CLIENT_SECRET
      key: secret/data/drone/config
      property: github_secret
    - name: DRONE_RPC_SECRET
      key: secret/data/drone/config
      property: rpc_secret
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: mongodb
  namespace: db
spec:
  backendType: vault
  data:
    - name: mongodb-root-password
      key: secret/data/mongodb/config
      property: mongodb_root_password