---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: hello-vault-service
  namespace: default
spec:
  backendType: vault
  data:
    - name: vault_pass
      key: secret/data/testapp/config
      property: password
    - name: vault_user
      key: secret/data/testapp/config
      property: username
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: drone
  namespace: devops
spec:
  backendType: vault
  data:
    - name: DRONE_GITHUB_CLIENT_ID
      key: secret/data/drone/drone
      property: github_id
    - name: DRONE_GITHUB_CLIENT_SECRET
      key: secret/data/drone/config
      property: github_secret
    - name: DRONE_RPC_SECRET
      key: secret/data/drone/config
      property: rpc_secret