---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: hello-vault-service
  namespace: default
spec:
  backendType: vault
  data:
    - name: vault_pass
      key: secret/data/testapp/config
      property: password
    - name: vault_user
      key: secret/data/testapp/config
      property: username
