---
{{- $serviceAccountCreate := .Values.serviceAccount.create | default false }}
{{- if $serviceAccountCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.env }}-{{ .Values.app.name }}-{{ .Values.app.slot }}
  labels:
    app: {{ .Values.app.name }}
    env: {{ .Values.app.env }}
    slot: {{ .Values.app.slot }}
    release: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}