image:
  pdbMinAvailable: 50%
  imagePullPolicy: "Always"

  replicas: 1

  envSecret:
    enabled: "true"

  containerPort: 3000
  livenessProbePath: "/healthz"
  readinessProbePath: "/healthz"
  initialDelaySeconds: 5

  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
    limits:
      cpu: "100m"
      memory: "100Mi"

prometheus:
  enabled: "false"

service:
  enabled: "true"
  type: ClusterIP
  port: 80

configMaps:
  enabled: "false"

serviceAccount:
  create: false