---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodejs
spec:
  interval: 1m0s
  releaseName: nodejs
  targetNamespace: namespace
  chart:
    spec:
      chart: ./charts/nodejs
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    app:
      name: nodejs
    image:
      replicas: "0"
      repo: docker-registry.registry:32080/nodejs
      tag: latest
