---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prod-app-nodejs
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./fluxcd/clusters/minikube/prod/apps/nodejs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
