---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: infra
spec:
  interval: 1m0s
  releaseName: external-secrets
  targetNamespace: infra
  chart:
    spec:
      chart: kubernetes-external-secrets
      version: '8.5.2'
      sourceRef:
        kind: HelmRepository
        name: kubernetes-external-secrets
  values:
    fullnameOverride: "external-secrets"
    env:
      LOG_LEVEL: debug
      VAULT_ADDR: http://192.168.49.1:8200
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
