apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs
  labels:
    app: nodejs
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "nodejs.minikube.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs
                port:
                  number: 80
