---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drone
  namespace: devops
  labels:
    app: drone
    release: drone
data:
  DRONE_SERVER_HOST: "drone.devops"
  DRONE_SERVER_PROTO: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: drone
  namespace: devops
  labels:
    app: drone
    release: drone
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: drone
    release: drone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  namespace: devops
  labels:
    app: drone
    release: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone
      release: drone
  template:
    metadata:
      labels:
        app: drone
        release: drone
    spec:
      containers:
        - name: server
          image: "drone/drone:1.9.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: DRONE_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: DRONE_GITHUB_CLIENT_ID
            - name: DRONE_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: DRONE_GITHUB_CLIENT_SECRET
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: DRONE_RPC_SECRET
          envFrom:
            - configMapRef:
                name: drone
          volumeMounts:
            - name: storage-volume
              mountPath: /data
              subPath: ""
      volumes:
        - name: storage-volume
          hostPath:
            path: /volume/drone/